export const strings = {
    startingFrom: 'startingFrom',
    perPerson: 'perPerson',
    requestQuote: 'requestQuote',
    requestQuoteDescription: 'requestQuoteDescription',
    fullName: 'fullName',
    phone: 'phone',
    email: 'email',
    eventType: 'eventType',
    eventDate: 'eventDate',
    guestCount: 'guestCount',
    message: 'message',
    sendRequest: 'sendRequest',
    required: 'required',
    invalidPhone: 'invalidPhone',
    invalidEmail: 'invalidEmail',
    leadSubmitted: 'leadSubmitted',
    leadError: 'leadError',
};
